---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.js"
exclude_paths:
- docs/js/scripts.js
- docs/js/highlight.min.js
- docs/js/jquery-ui.js
- docs/js/jquery.js
- docs/js/pug.js
- docs/css/docs.css
